
use azurhyan;

create table etat(
 ETATID integer NOT NULL AUTO_INCREMENT PRIMARY KEY,
 PERSONNAGE integer NOT NULL,
 DEDEF integer,
 TURNORDER integer NOT NULL,
 INCAPACITE integer DEFAULT 0,
 UNIQUE (PERSONNAGE),
 FOREIGN KEY (PERSONNAGE) REFERENCES personnages (PERSOID) ON DELETE CASCADE ON UPDATE CASCADE
);

commit;


